export const slots = [
  "Starts at Grove Street",
  "Return to Ganton",
  "Kill the person",
  "Go to the next checkpoint",
  "Many enemies but only one target to kill",
  "2500 health",
  "Enemy with headshots turned off",
  "Headshots on/off inconsistency",
  "Dead cop body object",
  "Shirtless old man is a zombie",
  "Enemy with overpowered accuracy",
  "Poorly translated mission",
  "Misspelled original character name",
  "'Groove Street'",
  "Travel to the other end of the map",
  "TO BE CONTINUED... (Or something like that)",
  "CJ player",
  "Gang mission",
  "MOTW mission",
  "Not part 1",
  "Part 1",
  "It is part of a mission pack",
  "Mission ends abruptly",
  "Invisible checkpoint",
  "Mission requires mods",
  "Has health and armor pickups",
  "Alternative SA story",
  "Player is from ballas or vagos",
  "Life simulation mission",
  "Mission made this year",
  "Mission made ten years ago or more",
  "Checkpoint near yellow marker without teleporting you to the interior",
  "Wanted stars enabled",
  "Wanted stars disabled",
  "Has explosive barrels",
  "Uses (parentheses) to represent sounds",
  "Zombie mission",
  "Mission crashes",
  "Uses Big Smoke's Palace interior",
  "Uses Meat Factory interior",
  "Misison name is 'DYOM'",
  "Mission author is 'DYOM'",
  "Does not start with a cutscene",
  "Starts at 8:00 AM",
  "Mission made by Target13",
  "Uses some random dancing animation",
  "Uses ramp object",
  "White marker",
  "Military mission",
  "Ball actor bug",
  "Go to LSPD Parking Lot",
  "Uses one of the police station interior",
];
